/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formularios;

import javax.swing.Icon;
import jiconfont.IconCode;
import jiconfont.swing.IconFontSwing;
import utiles.Constantes;

/**
 *
 * @author Alex
 */
public class MenuItem extends javax.swing.JPanel {
    private IconCode iconCode;
    private String nombre;
    private boolean isSeleccionado;
    
    /** Creates new form MenuItem */
    public MenuItem(IconCode ico, String nombre) {
        isSeleccionado = false;
        this.iconCode = ico;
        this.nombre = nombre;
        initComponents();
        initMenu();
        setName(nombre);
        
    }
    
    private void initMenu(){
        icono.setIcon(IconFontSwing.buildIcon(iconCode, 30, Constantes.COLOR_BLANCO));
    }
    
    public void setColor(){
        this.setBackground(Constantes.COLOR_MEDIO);
    }
    
    public void resetColor(){
        this.setBackground(Constantes.COLOR_PRIMARIO);
    }
    
    /*GETTER Y SETTERS*/

    public boolean isIsSeleccionado() {
        return isSeleccionado;
    }

    public void setIsSeleccionado(boolean isSeleccionado) {
        this.isSeleccionado = isSeleccionado;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        icono = new javax.swing.JLabel();

        setBackground(Constantes.COLOR_PRIMARIO);
        setMaximumSize(new java.awt.Dimension(2147483647, 60));
        setPreferredSize(new java.awt.Dimension(50, 60));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        jPanel3.setOpaque(false);

        icono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icono, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icono, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
       if(isSeleccionado) return;
       this.setColor();
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        if(isSeleccionado) return;
        this.resetColor();
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icono;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

}
