/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario.cliente;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import jiconfont.swing.IconFontSwing;
import modelos.Producto;
import recursos.iconos.GoogleMaterialDesignIcons;
import utiles.Constantes;

/**
 *
 * @author Alex
 */
public class PedidoItem extends javax.swing.JPanel {

    /**
     * Creates new form PedidoItem
     */
    public PedidoItem(Producto producto) {
        initComponents();
        lblCantidad.setText("x" + String.valueOf(producto.getCantidad()));
        lblProducto.setText(producto.getNombre());
        pintarIconos();
    }
    
    private void pintarIconos(){
        imagen.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.FASTFOOD, 30, Constantes.COLOR_BLANCO));
    }

    /*GETTER Y SETTERS*/
    public JLabel getLblCantidad() {
        return lblCantidad;
    }

    public JLabel getLblProducto() {
        return lblProducto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Dimension arcs = new Dimension(30, 30);
                int width = getWidth();
                int height = getHeight();
                Graphics2D graphics = (Graphics2D) g;
                graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                graphics.setColor(getBackground());
                graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); //paint background
                graphics.setColor(getForeground());
            }

        };
        imagen = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblCantidad = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();

        setBackground(Constantes.COLOR_BLANCO);
        setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 13, 3));
        setMaximumSize(new java.awt.Dimension(2147483647, 56));
        setOpaque(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(Constantes.COLOR_MEDIO);
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(60, 56));

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(Constantes.COLOR_BLANCO);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantidad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCantidad.setMaximumSize(new java.awt.Dimension(50, 1000));
        jPanel2.add(lblCantidad);

        lblProducto.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblProducto.setMaximumSize(new java.awt.Dimension(150, 1000));
        jPanel2.add(lblProducto);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        jPanel2.setBackground(new Color(250,250,250));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        jPanel2.setBackground(Constantes.COLOR_BLANCO);
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblProducto;
    // End of variables declaration//GEN-END:variables
}
