/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario.servidor;

import controlador.servidor.ControladorBloquearJButton;
import controlador.servidor.ControladorPanelResumen;
import java.awt.Image;
import javax.swing.ImageIcon;
import jiconfont.swing.IconFontSwing;
import modelos.Cliente;
import modelos.Pedido;
import recursos.iconos.GoogleMaterialDesignIcons;
import utiles.Constantes;

/**
 *
 * @author Alex
 */
public class ItemSolicitudPedido extends javax.swing.JPanel {
    private ControladorPanelResumen controladorPanelResumen;
    private Pedido pedido;
    private ControladorBloquearJButton controladorBloquearJButton;
    /**
     * Creates new form ItemSolicitudPedido
     */
    public ItemSolicitudPedido(Pedido pedido) {
        this.pedido = pedido;
        initComponents();
        pintarIconos();
        
        //Texto datos de este item
        lblNombre.setText("<html>"+pedido.getCliente().getNombre()+"</html>");
        lblTeléfono.setText("<html>"+pedido.getCliente().getTelefono()+"</html>");
        lblDireccion.setText("<html>"+pedido.getCliente().getDireccion()+"</html>");
        
        //Controlador del panel lateral derecho del resúmen del pedido
        controladorPanelResumen = new ControladorPanelResumen();
    }
    
    private void pintarIconos() {

        //Iconos de datos del cliente
        iconoUsuario.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.ACCOUNT_CIRCLE, 20, Constantes.COLOR_PRIMARIO));
        iconoDireccion.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.PLACE, 20, Constantes.COLOR_PRIMARIO));
        iconoTelefono.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.SMARTPHONE, 20, Constantes.COLOR_PRIMARIO));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagen = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        iconoUsuario = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTeléfono = new javax.swing.JLabel();
        iconoTelefono = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        iconoDireccion = new javax.swing.JLabel();
        btnAtender = new javax.swing.JButton();

        setBackground(new java.awt.Color(220, 220, 220));

        imagen.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                imagenComponentResized(evt);
            }
        });

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(iconoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 20));

        lblNombre.setBackground(Constantes.COLOR_BLANCO);
        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblNombre.setText("Nombre");
        lblNombre.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 100, 30));

        lblTeléfono.setBackground(Constantes.COLOR_BLANCO);
        lblTeléfono.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblTeléfono.setText("Teléfono");
        jPanel1.add(lblTeléfono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 20));

        iconoTelefono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(iconoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 30, 20));

        lblDireccion.setBackground(Constantes.COLOR_BLANCO);
        lblDireccion.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblDireccion.setText("Dirección");
        lblDireccion.setToolTipText("");
        lblDireccion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 100, 30));

        iconoDireccion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(iconoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 30, 20));

        btnAtender.setBackground(Constantes.COLOR_SECUNDARIO);
        btnAtender.setForeground(Constantes.COLOR_BLANCO);
        btnAtender.setText("Atender");
        btnAtender.setBorder(null);
        btnAtender.setBorderPainted(false);
        btnAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtender, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void imagenComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imagenComponentResized
        ImageIcon imagen1 = new ImageIcon(getClass().getResource("/recursos/iconos/Hamburguesa.jpg"));
        ImageIcon imagen2 = new ImageIcon(imagen1.getImage().getScaledInstance(imagen.getWidth(), imagen.getHeight(), Image.SCALE_DEFAULT));
        imagen.setIcon(imagen2);
    }//GEN-LAST:event_imagenComponentResized

    private void btnAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderActionPerformed
        controladorPanelResumen.setPedido(pedido);
        controladorPanelResumen.pintarPedido();
        controladorBloquearJButton = new ControladorBloquearJButton(btnAtender);
        controladorBloquearJButton.deshabilitar();
    }//GEN-LAST:event_btnAtenderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtender;
    private javax.swing.JLabel iconoDireccion;
    private javax.swing.JLabel iconoTelefono;
    private javax.swing.JLabel iconoUsuario;
    private javax.swing.JLabel imagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTeléfono;
    // End of variables declaration//GEN-END:variables
}
